### ISSUE TITLE
Conflict with Krypton - Server Crash When Client Attempts to Interact with server

### ISSUE THREAD

**Issue by Blobanium** [CardboardPowered/cardboard#103]
Hi so i opened an issue on Krypton's repo and they said the issue on bukkit4fabric's end so im opening one here

Link to the original issue
[Krypton Issue#9](https://github.com/astei/krypton/issues/9)

Crash log (For Quick Inspection)
[crash-2020-12-17_10.21.37-server.txt](https://github.com/BukkitFabric/bukkit4fabric/files/5712115/crash-2020-12-17_10.21.37-server.txt)

tell me if i need anything else to include

**Comment by IsaiahPatton** [comment]
Should now be fixed in the latest update.
