### ISSUE TITLE
CraftMagicNumbers.getMaterial(Item) can produce netty decoder NPE

### ISSUE THREAD

**Issue by CmdrJane** [CardboardPowered/cardboard#109]
Well if you go in game and grab any modded item that dont use vanilla materials you will get DCed instantly.
After some debug tinkering i found out that this is due to getMaterial method can return null values somehow.

Here's my fix for this, dont know tho is it even proper way to fix this but for me it works: https://pastebin.com/bqQ1zz9t

**Comment by IsaiahPatton** [comment]
Fixed in latest update
