### ISSUE TITLE
ProtocolLib not working fails load plugin

### ISSUE THREAD

**Issue by masterblaster221** [CardboardPowered/cardboard#120]
I'm on 1.16.4 it loads the server just not the plugin.  
same bug here. #82 i don't have the same plugins tho and its just ProtocolLib.
 here is the webpage https://www.spigotmc.org/resources/protocollib.1997/

**Comment by L0rdLogan** [comment]
Yeah: This is the error it throws me: https://pastebin.com/Y6Ea1u2C

**Comment by FarLanderCraft** [comment]
It's not working for me either ;-; .
I really want LibsDisguises ;-; .

**Comment by IsaiahPatton** [comment]
should be fixed now

**Comment by windy664** [comment]
> 现在应该修复
1.18.1 seems doesn't work
