### ISSUE TITLE
Multiverse Isn't compatible with Carboard even though their website says it does work.

### ISSUE THREAD

**Issue by anormalhedgehog** [CardboardPowered/cardboard#122]
I've been looking for a way to get plugins work on fabric and i tried to use Multiverse because it said on the website it "worked" even though multiverse isn't even compatible with bukkit and is only supported with paper and spigot, it gived me this error and just haulted the entire instance of the minecraft server "Multiverse-Core v4.2.2-b812" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.onarandombox.MultiverseCore.listeners.MVPortalListener.entityPortalCreate(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [dumptruckman, Rigby, fernferret, lithium3141, main--].

**Comment by L0rdLogan** [comment]
Now, I am not trying to defend Cardboard but it does work. - Where do you get the error? I can create a new world and TP to it in game

![image](https://user-images.githubusercontent.com/5092548/103371046-61386d00-4ac6-11eb-95eb-0c2f466f6d4d.png)

Original world:
![image](https://user-images.githubusercontent.com/5092548/103371063-6c8b9880-4ac6-11eb-840c-36bff4984c18.png)

I got multiverse from here: https://dev.bukkit.org/projects/multiverse-core

It may have a dedicated Spigot version you downloaded?

**Comment by IsaiahPatton** [comment]
You can ignore that error, it's just a warning that nultiverse uses a deprecated event. It happens on Spigot too: https://github.com/Multiverse/Multiverse-Core/issues/2000
