### ISSUE TITLE
Mod: Kibe inventories cannot be opened with B4F build 142 installed

### ISSUE THREAD

**Issue by L0rdLogan** [CardboardPowered/cardboard#125]
[13:11:02] [Server thread/INFO]: Using generic InventoryView for ScreenHandler (inventory provided by a mod?)

Ingame: Nothing happens

Removal of B4F results in:
![image](https://user-images.githubusercontent.com/5092548/103439281-5bac6580-4c33-11eb-87fc-45bbe8002a99.png)

**Comment by TheRealM18** [comment]
I can confirm this is a bug, but not just Kibe, but with Tech Reborn, too.

This if from the build that was done less then 16 hours ago.

**Comment by L0rdLogan** [comment]
Same bug exists in 148 :(

I haven't yet retried TechReborn as it used to completely halt the server

**Comment by IsaiahPatton** [comment]
modded inventories are fixed now
