### ISSUE TITLE
Modded Minecraft crashing

### ISSUE THREAD

**Issue by ZenoMetal** [CardboardPowered/cardboard#141]
`---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 1/19/21 8:17 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/bukkit/Material
	at org.bukkit.craftbukkit.util.CraftMagicNumbers.<clinit>(CraftMagicNumbers.java:94)
	at net.minecraft.class_3176.handler$zja000$init(class_3176.java:726)
	at net.minecraft.class_3176.method_3823(class_3176.java:155)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.bukkit.Material
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 6 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 5.8.13-100.fc31.x86_64
	Java Version: 1.8.0_272, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Red Hat, Inc.
	Memory: 731547112 bytes (697 MB) / 1863319552 bytes (1777 MB) up to 2863661056 bytes (2731 MB)
	CPUs: 80
	JVM Flags: 2 total; -Xms256M -Xmx3072M
	Fabric Mods: 
		adorn: Adorn 1.12.2+1.16.4
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.2
		anvil_fix: AnvilFix 1.1.3+build.7-1.16
		appleskin: AppleSkin 1.0.11
		artifacts: Artifacts 2.1.0+1.16.4-fabric
		autoconfig1u: Auto Config v1 Updated 3.3.1
		betterend: Better End 0.8.8-beta
		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
		byg: BYG 1.1.3
		cardboard: CardboardMod 149
		cardinal-components-base: Cardinal Components API (base) 2.7.9
		cardinal-components-entity: Cardinal Components API (entities) 2.7.9
		cardinal-components-item: Cardinal Components API (items) 2.7.9
		chainmail: Chainmail 0.5.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.3
		com_udojava_evalex: EvalEx 2.5
		continuebutton: Continue Button 1.0.2
		couplings: Couplings 1.3.3
		cursed_table: Cursed table 1.1.0
		customportalapi: customportalapi 0.0.1-beta18-1.16
		dynamo_api: Dynamo API 1.0.0+1.16.4
		elevator: Elevator Mod 1.0.0
		enchantmentdescriptions: Enchantment Descriptions 1.0.0
		engilib: EngiLib 1.0.0+1.16.4
		exotic-art-core: Exotic Art Core Content Pack 1.0.379
		exotic-art-tech: Exotic Art Tech Pack 1.2.379
		exotic-matter: Exotic Matter 2.12.381
		expandedstorage: ExpandedStorage 5.6.31
		fabric: Fabric API 0.29.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-flesh2leather: Fabric Rotten2Leather 1.0.0
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.1+0d4d7e343a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		facility: Facility 0.12.204
		fallflyinglib: FallFlyingLib 1.1.0
		falling_tree: FallingTree 2.10.0
		fermion: Fermion 2.9.218
		fermion-gui: Fermion GUI 2.5.218
		fermion-modkeys: Fermion Modifier Keys 1.10.218
		fermion-orientation: Fermion Orientation 1.2.218
		fermion-varia: Fermion Varia 2.6.218
		fiber: fiber 0.23.0-2
		fluidity: Fluidity 0.16.204
		givemehats: Give Me Hats! 1.4
		gobber2: Gobber2 2.3.49
		indrev: Industrial Revolution 1.7.15-BETA
		inmis: Inmis 2.1.1-1.16.4
		ironfurnaces: Iron Furnaces 2.4.0
		jankson: Jankson 3.0.1+j1.2.0
		jumploader: Jumploader 2.1.0
		kubejs: KubeJS 1.5.5
		lchunkloader: Literally Chunk Loader 1.3.3
		libblockattributes_core: LibBlockAttributes (Core) 0.8.3-pre.3
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.3-pre.3
		libblockattributes_items: LibBlockAttributes (Items) 0.8.3-pre.3
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.2.2+1.16.3
		magna: Magna 1.4.3-1.16.2
		mechanicaltech: Mechanical Tech 0.2.0+1.16.4
		mechanix: Mechanix 3.1.0
		minecraft: Minecraft 1.16.4
		netheritems: Nether Items 1.0.0
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		oro_config: OroArmor Config -0df99c92b1-1
		overpowered_mending: Overpowered Mending 2.2.2
		patchouli: Patchouli 1.16.4-48-FABRIC
		playerabilitylib: Pal 1.2.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.6.3+build.110
		roughlyenoughitems: Roughly Enough Items 5.8.10
		roughlyenoughitems-api: REI (API) 5.8.10
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.10
		roughlyenoughitems-runtime: REI (Runtime) 5.8.10
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		ruined_equipment: Ruined Equipment 1.2.2
		smithee: Smithee 0.1.5
		special-circumstances: Special Circumstances 1.8.218
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		supernaturalcrops: Supernatural Crops 1.0.6
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.7.3+build.192
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		trinket-heart-canisters: Trinket Heart Canisters 1.0.0
		trinkets: Trinkets 2.6.7
		vanilla-hammers: Vanilla Hammers 3.0.1-1.16.3
		waila: Hwyla 1.9.22
		waystones: Waystones 1.1.1.1
		winged: Winged Mod 1.16.2-1.4.1
		xaerominimap: Xaero's Minimap 21.1.0
		xaeroworldmap: Xaero's World Map 1.11.7
	Data Packs: vanilla (incompatible), file/VanillaTweaks_c679323.zip (incompatible), file/custom nether portals v2.2.1.zip (incompatible), file/double shulker shells v1.2.0.zip (incompatible), file/graves v2.6.5.zip (incompatible), file/more mob heads v2.6.2.zip (incompatible), file/villager death messages v1.1.0.zip (incompatible), Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)`

**Comment by L0rdLogan** [comment]
Try removing ExpandedStorage and retrying - the mod had issues last time I tried it

**Comment by ZenoMetal** [comment]
Did not help

**Comment by ChipWolf** [comment]
What fixed this for you @ZenoMetal, I assume it's solved if the issue is closed

**Comment by ZenoMetal** [comment]
@ChipWolf it was actually ExpandedStorage, but I stopped using Cardboard
