### ISSUE TITLE
Server crashes with Cardboard and Krypton

### ISSUE THREAD

**Issue by Phelms215** [CardboardPowered/cardboard#146]

**Comment by Phelms215** [comment]
Server crashes with Cardboard and Lithium, when I remove the Lithium, Phosphor and Krypton or Cardboard it works fine


`30.01 17:27:18 [Multicraft] Loading server properties
30.01 17:27:18 [Multicraft] Starting server!
30.01 17:27:18 [Multicraft] Loaded config for "FabricMC"
30.01 17:27:18 [Multicraft] Updating eula.txt file
30.01 17:27:20 [Server] main/INFO Loading for game Minecraft 1.16.5
30.01 17:27:21 [Server] main/INFO [FabricLoader] Loading 81 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, gunpowder-base@0.3.5+1.16.5, aopalliance_aopalliance@1.0, fabricloader@0.11.1, com_fasterxml_jackson_core_jackson-annotations@2.9.0, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.10+ca58154a7d, lithium@0.6.1, fabric-dimensions-v1@2.0.2+ca58154a7d, fabric-object-builder-api-v1@1.9.3+ca58154a7d, fabric-permissions-api-v0@0.1-SNAPSHOT, java@11, com_google_inject_guice@4.2.3, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.0+daa38b3d7d, org_jetbrains_exposed_exposed-core@0.27.1, org_postgresql_postgresql@42.2.2, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, javax_inject_javax_inject@1, com_fasterxml_jackson_core_jackson-databind@2.9.0, org_jetbrains_kotlin_kotlin-stdlib@1.4.21, playerabilitylib@1.2.1, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, com_fasterxml_jackson_dataformat_jackson-dataformat-yaml@2.9.0, fabric-renderer-registries-v1@2.2.1+ca58154a7d, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.21, luckperms@5.2.94, fabric-loot-tables-v1@1.0.2+ca58154a7d, com_fasterxml_jackson_core_jackson-core@2.9.0, org_slf4j_slf4j-api@1.8.0-beta1, fabric@0.30.0+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, org_jetbrains_exposed_exposed-jdbc@0.27.1, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, fabric-screen-handler-api-v1@1.1.1+ca58154a7d, dynmap@3.1-beta6, fabric-command-api-v1@1.0.10+ca58154a7d, phosphor@0.7.0+build.10, mysql_mysql-connector-java@5.1.46, fabric-screen-api-v1@1.0.0+c045166c7d, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.21, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.4.2, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-language-kotlin@1.4.21+build.1, fabric-entity-events-v1@1.0.3+ca58154a7d, cardboard@150, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.4.2, fabric-resource-loader-v0@0.4.2+ca58154a7d, org_jetbrains_kotlin_kotlin-reflect@1.4.21, fabric-content-registries-v0@0.2.1+ca58154a7d, org_xerial_sqlite-jdbc@3.28.0, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fastfurnace@2.3, org_jetbrains_exposed_exposed-java-time@0.27.1, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, krypton@0.1.1, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, gunpowder-utilities@1.0.2+gunpowder.0.3.1.mc.1.16.4, fabric-object-builders-v0@0.7.2+ca58154a7d, org_yaml_snakeyaml@1.26, com_fasterxml_jackson_module_jackson-module-kotlin@2.9.0, org_jetbrains_annotations@20.0.0
30.01 17:27:21 [Server] main/INFO SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/jar/fabricmc.jar Service=Knot/Fabric Env=SERVER
30.01 17:27:22 [Server] main/INFO Loaded configuration file for Lithium: 66 options available, 1 override(s) found
30.01 17:27:23 [Server] main/WARN Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
30.01 17:27:23 [Server] main/WARN @Mixin target net/minecraft/class_3898$class_3208 is public in mixins.utilities.gunpowder.json:EntityTrackerAccessor_Utilities and should be specified in value
30.01 17:27:23 [Server] main/WARN @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
30.01 17:27:23 [Server] INFO SLF4J: No SLF4J providers were found.
30.01 17:27:23 [Server] INFO SLF4J: Defaulting to no-operation (NOP) logger implementation
30.01 17:27:23 [Server] INFO SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
30.01 17:27:25 [Server] main/INFO [Dynmap] Mod Support API available
30.01 17:27:25 [Server] main/INFO Cardboard Mod - CardboardPowered.org
30.01 17:27:25 [Server] main/INFO (formerly known as Bukkit4Fabric)
30.01 17:27:26 [Multicraft] Received stop command
30.01 17:27:26 [Multicraft] Stopping server!
30.01 17:27:26 [Server] main/INFO Reflection working: true
30.01 17:27:26 [Server] main/INFO Cardboard mod Loaded.
30.01 17:27:26 [Server] main/FATAL Mixin apply failed krypton.mixins.json:network.shared.pipeline.encryption.ServerLoginNetworkHandlerMixin -> net.minecraft.class_3248: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("FIELD") on net/minecraft/class_3248::onKey$initializeVelocityCipher with priority 1000 cannot inject into net/minecraft/class_3248::method_12642(Lnet/minecraft/class_2917;)V merged by com.javazilla.bukkitfabric.mixin.network.MixinServerLoginNetworkHandler with priority 1000 [PREINJECT Applicator Phase -> krypton.mixins.json:network.shared.pipeline.encryption.ServerLoginNetworkHandlerMixin -> Prepare Injections ->  -> handler$zzh000$onKey$initializeVelocityCipher(Lnet/minecraft/class_2917;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
30.01 17:27:26 [Server] INFO org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("FIELD") on net/minecraft/class_3248::onKey$initializeVelocityCipher with priority 1000 cannot inject into net/minecraft/class_3248::method_12642(Lnet/minecraft/class_2917;)V merged by com.javazilla.bukkitfabric.mixin.network.MixinServerLoginNetworkHandler with priority 1000 [PREINJECT Applicator Phase -> krypton.mixins.json:network.shared.pipeline.encryption.ServerLoginNetworkHandlerMixin -> Prepare Injections ->  -> handler$zzh000$onKey$initializeVelocityCipher(Lnet/minecraft/class_2917;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
30.01 17:27:26 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
30.01 17:27:26 [Server] INFO at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
30.01 17:27:26 [Server] INFO at java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[?:?]
30.01 17:27:26 [Server] INFO at java.lang.Class.getDeclaredMethods(Class.java:2309) ~[?:?]
30.01 17:27:26 [Server] INFO at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:64) ~[fabricmc.jar:?]
30.01 17:27:26 [Server] INFO at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112) ~[fabricmc.jar:?]
30.01 17:27:27 [Multicraft] Server shut down (stopping)
30.01 17:27:27 [Multicraft] Server stopped`

**Comment by poohzaza166** [comment]
i have that issue but fix with build 150

**Comment by Phelms215** [comment]
This was when I was running the #150 build

**Comment by Phelms215** [comment]
Here is the crash without Krypton loaded

> 31.01 15:52:11 [Multicraft] Received start command
31.01 15:52:11 [Multicraft] Loading server properties
31.01 15:52:11 [Multicraft] Starting server!
31.01 15:52:11 [Multicraft] Loaded config for "FabricMC"
31.01 15:52:11 [Multicraft] Updating eula.txt file
31.01 15:52:15 [Server] main/INFO Loading for game Minecraft 1.16.5
31.01 15:52:15 [Server] main/INFO [FabricLoader] Loading 80 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, gunpowder-base@0.3.5+1.16.5, aopalliance_aopalliance@1.0, fabricloader@0.11.1, com_fasterxml_jackson_core_jackson-annotations@2.9.0, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.10+ca58154a7d, lithium@0.6.1, fabric-dimensions-v1@2.0.2+ca58154a7d, fabric-object-builder-api-v1@1.9.3+ca58154a7d, fabric-permissions-api-v0@0.1-SNAPSHOT, java@11, com_google_inject_guice@4.2.3, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.0+daa38b3d7d, org_jetbrains_exposed_exposed-core@0.27.1, org_postgresql_postgresql@42.2.2, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, javax_inject_javax_inject@1, com_fasterxml_jackson_core_jackson-databind@2.9.0, org_jetbrains_kotlin_kotlin-stdlib@1.4.21, playerabilitylib@1.2.1, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, com_fasterxml_jackson_dataformat_jackson-dataformat-yaml@2.9.0, fabric-renderer-registries-v1@2.2.1+ca58154a7d, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.21, luckperms@5.2.94, fabric-loot-tables-v1@1.0.2+ca58154a7d, com_fasterxml_jackson_core_jackson-core@2.9.0, org_slf4j_slf4j-api@1.8.0-beta1, fabric@0.30.0+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, org_jetbrains_exposed_exposed-jdbc@0.27.1, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, fabric-screen-handler-api-v1@1.1.1+ca58154a7d, dynmap@3.1-beta6, fabric-command-api-v1@1.0.10+ca58154a7d, phosphor@0.7.0+build.10, mysql_mysql-connector-java@5.1.46, fabric-screen-api-v1@1.0.0+c045166c7d, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.21, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.4.2, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-language-kotlin@1.4.21+build.1, fabric-entity-events-v1@1.0.3+ca58154a7d, cardboard@150, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.4.2, fabric-resource-loader-v0@0.4.2+ca58154a7d, org_jetbrains_kotlin_kotlin-reflect@1.4.21, fabric-content-registries-v0@0.2.1+ca58154a7d, org_xerial_sqlite-jdbc@3.28.0, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, fastfurnace@2.3, org_jetbrains_exposed_exposed-java-time@0.27.1, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, gunpowder-utilities@1.0.2+gunpowder.0.3.1.mc.1.16.4, fabric-object-builders-v0@0.7.2+ca58154a7d, org_yaml_snakeyaml@1.26, com_fasterxml_jackson_module_jackson-module-kotlin@2.9.0, org_jetbrains_annotations@20.0.0
31.01 15:52:15 [Server] main/INFO SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/jar/fabricmc.jar Service=Knot/Fabric Env=SERVER
31.01 15:52:17 [Server] main/INFO Loaded configuration file for Lithium: 66 options available, 0 override(s) found
31.01 15:52:17 [Server] main/WARN @Mixin target net/minecraft/class_3898$class_3208 is public in mixins.utilities.gunpowder.json:EntityTrackerAccessor_Utilities and should be specified in value
31.01 15:52:17 [Server] main/WARN @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
31.01 15:52:17 [Server] INFO SLF4J: No SLF4J providers were found.
31.01 15:52:17 [Server] INFO SLF4J: Defaulting to no-operation (NOP) logger implementation
31.01 15:52:17 [Server] INFO SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
31.01 15:52:20 [Server] main/INFO [Dynmap] Mod Support API available
31.01 15:52:20 [Server] main/INFO Cardboard Mod - CardboardPowered.org
31.01 15:52:20 [Server] main/INFO (formerly known as Bukkit4Fabric)
31.01 15:52:21 [Server] main/INFO Reflection working: true
31.01 15:52:21 [Server] main/INFO Cardboard mod Loaded.
31.01 15:52:21 [Server] main/FATAL Failed to start the minecraft server
31.01 15:52:21 [Server] INFO java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-networking-v0'!
31.01 15:52:21 [Server] INFO at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabricmc.jar:?]
31.01 15:52:21 [Server] INFO at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabricmc.jar:?]
31.01 15:52:21 [Server] INFO at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabricmc.jar:?]
31.01 15:52:21 [Server] INFO at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
31.01 15:52:21 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
31.01 15:52:21 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
31.01 15:52:21 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
31.01 15:52:21 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
31.01 15:52:21 [Server] INFO at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabricmc.jar:?]
31.01 15:52:21 [Server] INFO at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabricmc.jar:?]
31.01 15:52:21 [Server] INFO at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabricmc.jar:?]
31.01 15:52:21 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
31.01 15:52:21 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
31.01 15:52:21 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
31.01 15:52:21 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
31.01 15:52:21 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabricmc.jar:?]
31.01 15:52:21 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabricmc.jar:?]
31.01 15:52:21 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabricmc.jar:?]
31.01 15:52:21 [Server] INFO Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
31.01 15:52:21 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[fabricmc.jar:?]
31.01 15:52:21 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabricmc.jar:?]
31.01 15:52:21 [Multicraft] Server shut down (starting)
31.01 15:52:21 [Multicraft] Restarting crashed server in 5 seconds
31.01 15:52:21 [Multicraft] Server stopped

**Comment by QPCrummer** [comment]
I have the same issue

**Comment by notskamr** [comment]
> I have the same issue
Try to use Phosphor instead of Lithium. thats what i did.

**Comment by QPCrummer** [comment]
Lithium isn’t the issue, Krypton is. Also, lithium does basic AI and chunk loading improvements while phosphor does lighting improvements, so they optimize different parts of the game. Krypton does packet optimization.

**Comment by notskamr** [comment]
> Lithium isn’t the issue, Krypton is. Also, lithium does basic AI and chunk loading improvements while phosphor does lighting improvements, so they optimize different parts of the game. Krypton does packet optimization.

I kind of found a plausible cause. You might be using the wrong kind of fabric server. Instead of using Jumploader on forge, you should be using a pure fabric server which you can download. This will fix the issues with lithium, krypton, phosphor and most mods

**Comment by QPCrummer** [comment]
Nope, I use the fabric server jar and it still crashes.

**Comment by poohzaza166** [comment]
for me it work fine

**Comment by IsaiahPatton** [comment]
Should now be fixed in the latest update.
