### ISSUE TITLE
Plugin Potions not working

### ISSUE THREAD

**Issue by EnvyEnfys** [CardboardPowered/cardboard#149]
https://gyazo.com/dbe2cad3b62303ff50d6e5ab837fba34
When you try and drink them that happens 
Log https://cdn.discordapp.com/attachments/724818113568178246/803423811529343036/latest_1.log

**Comment by choalover** [comment]
Did you try updating to the latest version of Cardboard?

**Comment by IsaiahPatton** [comment]
Potions are now fixed in latest update (commit https://github.com/CardboardPowered/cardboard/commit/53b1e227a8a524d0c8f353a0ece94cdbba85f978)
