### ISSUE TITLE
Bigdoors not working

### ISSUE THREAD

**Issue by bonn2** [CardboardPowered/cardboard#150]
Tested Bigdoors and it has an error on player join event that is not present when running on the latest [Paper #447](https://papermc.io/downloads). The version of bigdoors used is [Alpha 0.1.8.28](https://www.spigotmc.org/resources/big-doors.58669/update?update=375809). After this error, the gui does not work which is expected, however using the command /newdoor to avoid the gui does not work (with no errors in the console) despite all the events that should it need (playerinteractevent) being marked as implemented in the TODO list.

Here is the log [https://pastebin.com/Gd8RyT6A](https://pastebin.com/Gd8RyT6A)

Hope this helps you guys (I am a moderator of the BigDoors support team so I should be able to help answer some questions if yall have any)

**Comment by IsaiahPatton** [comment]
The NullPointerException should be fixed in the latest update now.
