### ISSUE TITLE
Hopper to hopper transfer broken.

### ISSUE THREAD

**Issue by igamerized** [CardboardPowered/cardboard#153]
Transfers between hoppers operate at an extremely unusual speed. Hoppers to chests operate as one would expect, but hoppers do not. I've tested this on both the official test server and on a private server with only the newest official build of Cardboard installed on it. See the video below for further clarification.

**Here is the clip of hoppers not working on the official test server, I've tested this on both the test server and on a local server with the newest Cardboard build**
[https://streamable.com/2pvgge](url)

For continuity, I also tested the hopper issue on both clean installs of Spigot and Paper. The bug is not present on either of these so I do believe the issue is unique with Cardboard.

**Test on Spigot build**
[https://streamable.com/93jb28](url)

**Test on Paper build**
[https://streamable.com/1e5f23](url)

**Comment by IsaiahPatton** [comment]
should be fixed now
