### ISSUE TITLE
Server gets stuck on Preparing Spawn Area

### ISSUE THREAD

**Issue by evan-wsw** [CardboardPowered/cardboard#158]
When I run my server with this mod, everything in the server console looks fine until I get to the part where it prepares the spawn area. In there, it gets stuck at a percentage between 1 and 100 and the CPU usage of the server goes down to 0 in task manager. The fabric mods I have are: 
appleskin, BBOR, BetterCaves, BetterMineshafts, cardboard, fabric api, fabric kotlin language, mumblelink, fastfurnace, hypnos, immersive portals, PaI, simplexterrain, stackable stew, and Yung's API. 

The plugins I have are essentialsX, essentialsXChat, essentialsXSpawn, and LuckPerms. I have already tried removing all of the plugins and it still comes up with that issue.

**Comment by choalover** [comment]
Immersive Portals is incompatible with Cardboard so you have to remove Immersive Portals or Cardboard.

**Comment by evan-wsw** [comment]
Got it, thanks
