### ISSUE TITLE
Server Issues

### ISSUE THREAD

**Issue by CyanPoptart** [CardboardPowered/cardboard#159]
I'm not sure if this is a server-side only mod, but I could only connect to my server when it wasn't in my own mods folder. My server is a Fabric 1.16.5 server running the Origins mod and Fabric API, but nothing else. Once I got in, the Bukkit SinglePlayerSleep2 plugin didn't work at all and whenever I tried to use the Bukkit Armor Stand Edit plugin, the GUI would pop up and then I'd get disconnected. I then tried removing all the plugins and putting cardboard into my mods folder, and I was able to join, but nobody else was able to join. Any idea on what the problem is? Solutions would also be much appreciated :)

**Comment by VanillaChan6571** [comment]
Please mark this close since this is not an issue. These things you say are still on TODO list. You can see them on #9.
