### ISSUE TITLE
Incompatible with Requiem

### ISSUE THREAD

**Issue by gabrielmaster123** [CardboardPowered/cardboard#160]
The cmd window closes with no crash report but this log. I already removed the expanded storage mod. Running on 1.16.5
[latest.log](https://github.com/CardboardPowered/cardboard/files/6014897/latest.log)

Edit:
`[13:03:06] [main/FATAL]: Mixin apply failed mixins.requiem.common.json:remnant.LivingEntityMixin -> net.minecraft.class_1309: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_1309::dropUsedItemAsSoul with priority 1000 cannot inject into net/minecraft/class_1309::method_6040()V merged by com.javazilla.bukkitfabric.mixin.entity.MixinLivingEntity with priority 1000 [PREINJECT Applicator Phase -> mixins.requiem.common.json:remnant.LivingEntityMixin -> Prepare Injections ->  -> handler$bdg000$dropUsedItemAsSoul(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1309::dropUsedItemAsSoul with priority 1000 cannot inject into net/minecraft/class_1309::method_6040()V merged by com.javazilla.bukkitfabric.mixin.entity.MixinLivingEntity with priority 1000 [PREINJECT Applicator Phase -> mixins.requiem.common.json:remnant.LivingEntityMixin -> Prepare Injections ->  -> handler$bdg000$dropUsedItemAsSoul(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]`

**Comment by IsaiahPatton** [comment]
Should be fixed now
