### ISSUE TITLE
My server stops

### ISSUE THREAD

**Issue by RedDragon204** [CardboardPowered/cardboard#164]
My server for apex hosting stops at around 90%, I'm not sure what to do.

[
![Server, not responding](https://user-images.githubusercontent.com/71540691/109373918-8a773e80-7866-11eb-9bd2-f818866ccb6d.png)
](url)

**Comment by L0rdLogan** [comment]
What mods? it looks like you may be using Immersive Portals

**Comment by RedDragon204** [comment]
I am, is it a conflicting mod? I'm also using quite a few others as well.

**Comment by RedDragon204** [comment]
Also tried it by itself in a secondary server and it wont let you log into it.

**Comment by ZenithAstralis** [comment]
Immersive Portals is a conflicting mod, yes

**Comment by IsaiahPatton** [comment]
> Immersive Portals is a conflicting mod, yes

Closing in favor of #27
