### ISSUE TITLE
Carboard not compatible C2ME mod

### ISSUE THREAD

**Issue by ghost** [CardboardPowered/cardboard#170]
![8129_5ff0846ba4370](https://user-images.githubusercontent.com/71688822/111183039-8c5c3400-85c0-11eb-8ddb-eb7ae83cb675.jpg)

**Mod build**: 16
**Version Carboard**: 152
**Fabric version**: 0.7.2
**Crash-report**:  [crash-2021-03-15_15.54.07-server.txt](https://github.com/CardboardPowered/cardboard/files/6142718/crash-2021-03-15_15.54.07-server.txt)

**Mode installed**:
Carboard, C2ME

Link on error mod: [ https://github.com/YatopiaMC/C2ME-fabric](url)

EDIT: `PRIVATE @Overwrite method method_17228 in c2me.mixins.json:threading.chunkio.MixinThreadedAnvilChunkStorage cannot reduce visibiliy of PUBLIC target method`

**Comment by LuciphronNaxtel** [comment]
Try using fabric stalker for version 0.6.1.51
Let me know if that corrects the issue
