### ISSUE TITLE
Cardboard 153 broken

### ISSUE THREAD

**Issue by DeZoWaRe** [CardboardPowered/cardboard#171]
![8129_5ff0846ba4370](https://user-images.githubusercontent.com/71688822/111183039-8c5c3400-85c0-11eb-8ddb-eb7ae83cb675.jpg)

**Version Carboard**: 153
**Fabric version**: 0.7.2
**Info**: I installed build 153 for 11 and 8 Java, I tried to do it on my pc and on 3 hosts where I got an error! 152 build good work!
**Crash-report**: [message.txt](https://github.com/CardboardPowered/cardboard/files/6142796/message.txt)

**Comment by IsaiahPatton** [comment]
Should be fixed now
