### ISSUE TITLE
ProtocolLib not working, important plugin!

### ISSUE THREAD

**Issue by DeZoWaRe** [CardboardPowered/cardboard#173]
![8129_5ff0846ba4370](https://user-images.githubusercontent.com/71688822/111183039-8c5c3400-85c0-11eb-8ddb-eb7ae83cb675.jpg)

**Plugin version**: 4.6.0
**Version Carboard**: 152
**Fabric version**: 0.7.2
**Report**:  
[message.txt](https://github.com/CardboardPowered/cardboard/files/6142979/message.txt)

**Info**: The fix for this plugin is very important, since the most necessary plugins for servers work on it, I will look forward to solving this problem!

**Mode installed**:
Carboard

**Plugin installed**: 
ProtocolLib

**Link on error plugin**: [https://www.spigotmc.org/resources/protocollib.1997/](url)

**Comment by infintesial2** [comment]
im having same problem

**Comment by IsaiahPatton** [comment]
should be fixed now
