### ISSUE TITLE
User Authenticator [STDERR]

### ISSUE THREAD

**Issue by ghost** [CardboardPowered/cardboard#178]
![8129_5ff0846ba4370](https://user-images.githubusercontent.com/71688822/111183039-8c5c3400-85c0-11eb-8ddb-eb7ae83cb675.jpg)

**Version Carboard**: 152
**Fabric version**: 0.7.2
**Report**:  
[latest.log](https://github.com/CardboardPowered/cardboard/files/6166482/latest.log)

**Mode installed**:
Carboard, starlight-fabric-0.0.2

**Plugin installed**: 
![Без имени](https://user-images.githubusercontent.com/71688822/111677721-8a98a780-8830-11eb-963f-a8e881f3db6e.png)

**Comment by IsaiahPatton** [comment]
Should be fixed now
