### ISSUE TITLE
Failed to Start Server

### ISSUE THREAD

**Issue by chrishdx** [CardboardPowered/cardboard#182]
Hi,

whenever I want to start the server it stops loading but if I leave out the mod, it starts normally. Attached is the bug report.
[Fehler.txt](https://github.com/CardboardPowered/cardboard/files/6204921/Fehler.txt)

**Comment by Redev837** [comment]
Same issue

**Comment by IsaiahPatton** [comment]
Now fixed in https://github.com/CardboardPowered/cardboard/commit/e93c34aef476abef9b776c1998fee1d4605b41b0
