### ISSUE TITLE
Incompatible with Floodgate fabric

### ISSUE THREAD

**Issue by humematt190** [CardboardPowered/cardboard#188]
I want to switch my server from paper to fabric so i can use lithium and phosphor but i still want to use plugins

I put floodgate in the mods folder with lithium phosphor and cardboard
it just crashes for some reason

here are my logs: https://mclo.gs/9JsvTSj

**Comment by humematt190** [comment]
also the plugins don't work either

**Comment by Camotoy** [comment]
Specifically, the incompatibility lies with Floodgate-Fabric and this mixin: https://github.com/GeyserMC/Floodgate-Fabric/blob/master/src/main/java/org/geysermc/floodgate/mixin/ServerNetworkIoMixin.java, which conflicts with https://github.com/CardboardPowered/cardboard/blob/master/src/main/java/com/javazilla/bukkitfabric/mixin/network/MixinServerNetworkIo.java#L65. I'm not sure what the best solution for this is, but I'm happy to fix it on our end. 

Geyser-Fabric should work fine with Cardboard.

**Comment by L0rdLogan** [comment]
Issue is to be fixed in build 156

**Comment by IsaiahPatton** [comment]
Should be fixed in build 156 (commit: https://github.com/CardboardPowered/cardboard/commit/1dd53b824140d87bdc9990ea60b29b40370fe1f3) now.

**Comment by humematt190** [comment]
thanks i'll try it

**Comment by humematt190** [comment]
thanks it worked
