### ISSUE TITLE
Architectury API Incompatibility, entrypoint issue?

### ISSUE THREAD

**Issue by jbjornberg** [CardboardPowered/cardboard#192]
https://pastebin.com/pJ36sEcn
To replicate the issue, install [Cardboard](https://www.curseforge.com/minecraft/mc-mods/cardboard) & [Architectury API (Fabric)](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric) along with the necessities needed to run Fabric.

Both mods work fine independently of each other, this is the only incompatibility in my 200+ modpack so far- (only Architectury and Cardboard are ran in the above pastebin though) so any help would be appreciated.

This is probably relevant to mention, but due to it being incompatible with Architectury, it's inherently incompatible with the following:
[FTB GUI Library (Fabric)](https://www.curseforge.com/minecraft/mc-mods/ftb-gui-library-fabric)
[FTB Ultimine (Fabric)](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric)
[FTB Quests (Fabric)](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric)
[FTB Teams (Fabric)](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric)
[KubeJS (Fabric)](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric)
[And more...](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric/relations/dependents?filter-related-dependents=3)

**Comment by jbjornberg** [comment]
The Architectury developer has recently stated that they do not plan on fixing this. Do you think it would be realistically possible for you to fix this on your end?

**Comment by IsaiahPatton** [comment]
Will fix soon.
[&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;](https://github.com/CardboardPowered/cardboard/blob/master/src/main/java/com/javazilla/bukkitfabric/mixin/network/MixinServerPlayNetworkHandler.java#L267)

**Comment by IsaiahPatton** [comment]
Fixed now in build 157
