### ISSUE TITLE
Can't view people's names in chat

### ISSUE THREAD

**Issue by TazerMonkey5** [CardboardPowered/cardboard#193]
When I have this mod installed and me or anyone in my server speak there name isn't listed. My mods are, origins, extra origins pehkui and fabric API.

**Comment by xiajibaluanshuo** [comment]
The player joined the team?

**Comment by SaltNuggets** [comment]
I also have this issue with the same mods

**Comment by Snoe0** [comment]
I have this issue even with just Sodium, Phosphor, and Cardboard.

**Comment by IsaiahPatton** [comment]
Should be fixed
