### ISSUE TITLE
Cardboard Won't Work With CoreProtect

### ISSUE THREAD

**Issue by DoubleZPlaying** [CardboardPowered/cardboard#195]
My server won't start when Deltalogger is installed on the server with Cardboard, and CoreProtect simply won't work. Apparently, the plugin is "disabled"

**Comment by IsaiahPatton** [comment]
Deltalogger support should be fixed now. I'll look into why CoreProtect is not working soon.

**Comment by DoubleZPlaying** [comment]
> Deltalogger support should be fixed now. I'll look into why CoreProtect is not working soon.

Any progress?

**Comment by IsaiahPatton** [comment]
It should be fixed now (commit: https://github.com/CardboardPowered/cardboard/commit/5958eab669b556ec640a22d0457c397c82e286f8)
