### ISSUE TITLE
Typing in chat appears empty

### ISSUE THREAD

**Issue by ShadowCresendo** [CardboardPowered/cardboard#204]
Whenever I type anything in chat and enter it into chat it just appears empty with nothing in it.
![image](https://user-images.githubusercontent.com/35414331/117566291-1eab2080-b0b6-11eb-8812-95f639d4e669.png)

Edit: I should probably put the mods list on here too
![image](https://user-images.githubusercontent.com/35414331/117566522-536ba780-b0b7-11eb-81ae-e5e4bedb16b9.png)

**Comment by L0rdLogan** [comment]
Any plugins?

**Comment by ShadowCresendo** [comment]
I forgot to close this since I found the issue being a mod. My bad.
