### ISSUE TITLE
EssentialsX does not work

### ISSUE THREAD

**Issue by TheBACKTRACK** [CardboardPowered/cardboard#206]
Server gives me this error:
[Bukkit] Error occurred while enabling Essentials v2.18.2.0 (Is it up to date?)

**Comment by bonn2** [comment]
There is a patched version of EssX https://cardboardpowered.org/essentialsx/

**Comment by TheBACKTRACK** [comment]
> 
> 
> There is a patched version of EssX https://cardboardpowered.org/essentialsx/

Thank you
