### ISSUE TITLE
Bukkit, Spigot + Paper API ?

### ISSUE THREAD

**Issue by PhoenixIV** [CardboardPowered/cardboard#212]
From my understanding all three have different APIs. Paper extends Spigot which extends Bukkit. It is not clear to me if all Paper plugins will run with this mod, or only Bukkit API plugins?

Maybe add some extra information to the project start page?

**Comment by Obydux** [comment]
This project is trying to support these APIs , though the project is far away from being finished. If you have any questions you should join the Cardboard Discord server

**Comment by PhoenixIV** [comment]
Discord is not a good place to solve questions for more than one person / publicly. However, thanks! 😊
