### ISSUE TITLE
crashes fabric server on 1.16.5 java 16

### ISSUE THREAD

**Issue by frickinfire** [CardboardPowered/cardboard#218]
22.06 19:31:08 [Server] main/INFO SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/jar/custom-java11.jar Service=Knot/Fabric Env=SERVER
22.06 19:31:08 [Server] INFO Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
22.06 19:31:08 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:52)
22.06 19:31:08 [Server] INFO Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
22.06 19:31:08 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:108)
22.06 19:31:08 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50)
22.06 19:31:08 [Server] INFO Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
22.06 19:31:08 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:64)
22.06 19:31:08 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106)
22.06 19:31:08 [Server] INFO ... 1 more
22.06 19:31:08 [Server] INFO Caused by: java.lang.reflect.InvocationTargetException
22.06 19:31:08 [Server] INFO at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22.06 19:31:08 [Server] INFO at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22.06 19:31:08 [Server] INFO at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22.06 19:31:08 [Server] INFO at java.base/java.lang.reflect.Method.invoke(Method.java:566)
22.06 19:31:08 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62)
22.06 19:31:08 [Server] INFO ... 2 more
22.06 19:31:08 [Server] INFO Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config bukkitfabric.mixins.json
22.06 19:31:08 [Server] INFO at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
22.06 19:31:08 [Server] INFO at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
22.06 19:31:08 [Server] INFO at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
22.06 19:31:08 [Server] INFO at net.fabricmc.loader.launch.common.FabricMixinBootstrap.addConfiguration(FabricMixinBootstrap.java:44)
22.06 19:31:08 [Server] INFO at java.base/java.lang.Iterable.forEach(Iterable.java:75)
22.06 19:31:08 [Server] INFO at net.fabricmc.loader.launch.common.FabricMixinBootstrap.init(FabricMixinBootstrap.java:83)
22.06 19:31:08 [Server] INFO at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132)
22.06 19:31:08 [Server] INFO at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28)
22.06 19:31:08 [Server] INFO ... 7 more
22.06 19:31:08 [Server] INFO Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_16 could not be set. Level is not supported
22.06 19:31:08 [Server] INFO at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1493)
22.06 19:31:08 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:494)
22.06 19:31:08 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:463)
22.06 19:31:08 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:392)
22.06 19:31:08 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1093)
22.06 19:31:08 [Server] INFO at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
22.06 19:31:08 [Server] INFO ... 14 more
22.06 19:31:08 [Multicraft] Server shut down (starting)
22.06 19:31:08 [Multicraft] Restarting crashed server in 600 seconds
22.06 19:31:08 [Multicraft] Stopping server!
22.06 19:31:10 [Multicraft] Looks like a crash, check the server console. Return value: 1
22.06 19:31:10 [Multicraft] Server stopped

**Comment by SinanGentoo** [comment]
same

**Comment by IsaiahPatton** [comment]
> The requested compatibility level JAVA_16 could not be set. Level is not supported
Requires Java 16 & The latest Fabric loader.
