### ISSUE TITLE
no main manifest attribute, in server.jar

### ISSUE THREAD

**Issue by SoupOrSoda** [CardboardPowered/cardboard#219]
:/home/container$ java -Xms128M -Xmx7500M -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
no main manifest attribute, in server.jar
container@pterodactyl~ Server marked as offline...

**Comment by IsaiahPatton** [comment]
Cardboard is a Fabric mod, you don't run the mod jar directly
