### ISSUE TITLE
Crashing on joining 1.17 Experimental

### ISSUE THREAD

**Issue by Ashley123477** [CardboardPowered/cardboard#227]
The moment i join the server it crashes, No plugins installed, Mods are 
fabric-api-0.36.1+1.17.jar
CardboardMod-1.17.jar

Crash report linked

[crash-2021-07-10_23.39.00-server.txt](https://github.com/CardboardPowered/cardboard/files/6796056/crash-2021-07-10_23.39.00-server.txt)

**Comment by IsaiahPatton** [comment]
This should be fixed now.
