### ISSUE TITLE
Add purpur to server

### ISSUE THREAD

**Issue by TheAwesome98-Real** [CardboardPowered/cardboard#228]
this has bukkit spigot and paper but you could add purpur and have it be even faster

**Comment by bonn2** [comment]
This is an implementation of apis, not performance patches

**Comment by TheAwesome98-Real** [comment]
ok

**Comment by nevetS-718** [comment]
The api patches aren't useful in any of the bukkit nor spigot plugins, so it would be fairly useless

**Comment by TheAwesome98-Real** [comment]
ok
