### ISSUE TITLE
Cross Dimension Teleportation. (/Home, /Warp, /Spawn) Bssentials

### ISSUE THREAD

**Issue by RichardIsSoarx** [CardboardPowered/cardboard#237]
Teleportation works as intended. Until you attempt to teleport between worlds. You can teleport to the nether or end dimensions, and between them. But when you attempt to get to teleport back to a home in the over-world. It takes you to that location in the current dimension you are in. And this happens for the /Spawn command as well. You get  to the End Spawn. Not the Over-world Spawn.

**Comment by leucome** [comment]
I have the similar teleporting and spawn issue with Multiverse-core and portal.
