### ISSUE TITLE
LivingEntityImpl is not a subtype of AbstractHorse.

### ISSUE THREAD

**Issue by TwoPointInfinity** [CardboardPowered/cardboard#324]
`java.lang.ClassCastException: class org.cardboardpowered.impl.entity.LivingEntityImpl cannot be cast to class org.bukkit.entity.AbstractHorse (org.cardboardpowered.impl.entity.LivingEntityImpl and org.bukkit.entity.AbstractHorse are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @224edc67)`

The module info in the message is misleading. This is a case of trying to cast something to something that doesn't match it

Until this is fixed Cardboard is virtually unusable for survival servers.

**Comment by IsaiahPatton** [comment]
Should be fixed now.
