### ISSUE TITLE
Added a few more mods than just the phosphor things and then this happend

### ISSUE THREAD

**Issue by Saladdddd** [CardboardPowered/cardboard#39]
I know i can just remove the mods again, but i guess you would want this to work with most of the mods
[crash-2020-10-20_18.20.30-server.txt](https://github.com/BukkitFabric/bukkit4fabric/files/5410086/crash-2020-10-20_18.20.30-server.txt)
the german parts say "process cant access file because another process has locked it" or something like that
[latest.log](https://github.com/BukkitFabric/bukkit4fabric/files/5410092/latest.log)
[2020-10-20-1.log](https://github.com/BukkitFabric/bukkit4fabric/files/5410095/2020-10-20-1.log)

**Comment by IsaiahPatton** [comment]
Should be fixed now
