### ISSUE TITLE
joining a server with discordsrv crashes

### ISSUE THREAD

**Issue by arceuss** [CardboardPowered/cardboard#41]
everything else works but joining the server crashes the server instantly
[crash-2020-10-21_14.29.01-server.txt](https://github.com/BukkitFabric/bukkit4fabric/files/5418764/crash-2020-10-21_14.29.01-server.txt)

**Comment by EvilSquirrelGuy** [comment]
Use fabric-discord link mod for fabric, it works well

**Comment by IsaiahPatton** [comment]
DiscordSRV should load now. Although the fabric alternative is better.
