### ISSUE TITLE
TAB plugin does not load

### ISSUE THREAD

**Issue by OneDefauter** [CardboardPowered/cardboard#64]
https://pastebin.com/8DTzi92e

https://www.spigotmc.org/resources/tab-1-5-x-1-16-4.57806/

**Comment by Toshimichi0915** [comment]
TAB relies on Spigot's [native source code](https://github.com/NEZNAMY/TAB/blob/9d0a3448a44bb74ee6c9ce814323366b179f1f8a/src/main/java/me/neznamy/tab/platforms/bukkit/nms/NMSHook.java).
This problem will never fixed until the owner of the plugin add a support for fabric, which I believe won't occur.
