### ISSUE TITLE
SignChangeEvent

### ISSUE THREAD

**Issue by fantahund** [CardboardPowered/cardboard#68]
If you put a sign, it describes it and press done you will be kicked with the following message.

[04:43:35] [Server thread/INFO]: fantahund lost connection: Internal Exception: java.lang.IllegalStateException: SignChangeEvent cannot be triggered asynchronously from another thread.
[04:43:35] [Server thread/INFO]: fantahund left the game

**Comment by kristibektashi** [comment]
#9

**Comment by fantahund** [comment]
> #9

???

**Comment by kristibektashi** [comment]
Look in issue #9 (pinned issue) to see which events have been implemented and if SignChangeEvent exists on Bukkit4Fabric or not

**Comment by PapiOphidian** [comment]
+1 to original error. SignChangeEvent is a valid event in issue 9, but it's kicking players who place signs (even with no text).

**Comment by IsaiahPatton** [comment]
Fixed in https://github.com/CardboardPowered/cardboard/commit/b86fa1f434ccbd0945e05704b568b717db877b60
