### ISSUE TITLE
ProtocolLib not working at all (minecraft 1.16.4)

### ISSUE THREAD

**Issue by kristibektashi** [CardboardPowered/cardboard#82]
https://hastebin.com/arapacobah.properties

This might also be an issue with the plugin itself because 1.16 support is still experimental

I have WorldEdit, WorldGuard, Vault, ProtocolLib, bukkit4fabric and fabric api installed

**Comment by kristibektashi** [comment]
I forgot to say that I am using build 129

**Comment by L0rdLogan** [comment]
Build 142, it is still an issue:

https://pastebin.com/Y6Ea1u2C

**Comment by IsaiahPatton** [comment]
should be fixed now
