### ISSUE TITLE
Item Spawn or Item Craft Disconnect Issue (#134)

### ISSUE THREAD

**Issue by RawrMaoster** [CardboardPowered/cardboard#93]
This happens in random mods on specific items.

If let's say i try to craft a hammer it will disconnect me either as soon as i click to craft or as soon as i put it in my hotbar/inventory. 

9 times out of 10 its when i drop it in my inventory.

https://pastebin.com/rJgVFuLL

In the link above you'll see an array of errors of me trying to click items in survival in REI (mod that displays items when your in an inventory) and when i go into creative you'll see me disconnect when i put an item in my inventory from REI. Same error if crafted manually. Same error if i pull the offending items from minecrafts search function instead of using REI.

This happens with and without plugins and happens when mod is installed. Without all works as intended.

Want any more information etc let me know.

Thanks,
RawrMaoster#1234

**Comment by IsaiahPatton** [comment]
Should be fixed in latest update now
