### ISSUE TITLE
Unable to start server with DimensionalThreadding installed 

### ISSUE THREAD

**Issue by Blobanium** [CardboardPowered/cardboard#96]
i opened an issue over there on DimensionalThreadding's repo explaining it and they told me the issue was on bukkit4fabric's end so i sent a link directing to the issue.

[DimensionalThreadding Issue#8](https://github.com/WearBlackAllDay/DimensionalThreading/issues/8#issue-756693382)

tell me if i need anything to include

**Comment by WearBlackAllDay** [comment]
The issue is this mod does not utilize the Server object issued with vanilla, but a custom variant of it.

**Comment by IsaiahPatton** [comment]
Fixed in https://github.com/CardboardPowered/cardboard/commit/91c919a19cd00b2eac55fd6275da1a635b7b1ca6, Bukkit will now detect DimensionalThreadding's threads as safe for world IO
